### ISSUE TITLE
Improve contextual help for "Solr field for Creative Commons license URI" admin setting

### ISSUE THREAD

**Issue by mjordan** [bondjimbond/islandora_creative_commons#1]
The help text for the "Solr field for Creative Commons license URI" admin settings field says "Solr field that contains the CC license URI." but it might useful to provide some specific guidance when choosing a MODS field. Also, if the field isn't multivaluded (e.g., ends in `_m`) you get a PHP array error. How about something like

> Solr field for Creative Commons license URI. Must be multivalued (e.g., has a _m at the end of the field name).

This is consistent with what the README says: "Solr field for Creative Commons license URI: Defaults to mods_accessCondition_ms. Multivalued field recommended if working with other accessCondition fields."

Also, the value currently defaults to `dc.rights`,  not `mods_accessCondition_ms`.

I'm happy to open a PR to address these points if you want.

**Comment by bondjimbond** [comment]
Please do, thanks!

**Comment by bondjimbond** [comment]
Fixed with #2
